version: '3'
services:
    db:
        image: mysql:5.7
        env_file: .env
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

    mongo:
        image: mongo:3.6.13
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

    app:
        image: d9magai/treefrogframework
        command: sh -c 'make && rm -f tmp/treefrog.pid && treefrog -e dev'
        working_dir: /srv
        tty: true
        volumes:
            - document_root:/srv
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
        user: "${uid}:${gid}"
        depends_on:
            - db
            - mongo
        ports:
            - "0.0.0.0:8800:8800"

volumes:
    document_root:
        driver_opts:
            type: none
            device: ${PWD}/app/
            o: bind

